"""Contextual subject corpus ported from C# Lookup.cs."""

DATA = {
  "andrew": {
    "work": {
      "9": "Work gives purpose and builds character.",
      "4": "Stress creeps in with looming deadlines.",
      "5": "Routine creates stability and steady income.",
      "1": "Burnout makes passion feel like burden.",
      "3": "Long hours drain energy and joy.",
      "0": "Work traps many in endless cycles.",
      "2": "Micromanagement kills creativity and motivation.",
      "6": "Challenges push skills beyond their limits.",
      "7": "Achievements bring pride and satisfaction.",
      "8": "Collaboration sparks innovation and growth daily."
    },
    "procrastination": {
      "9": "Procrastination sparks my best creative ideas.",
      "4": "I waste time, then stress hits.",
      "5": "Sometimes waiting brings unexpected clarity.",
      "1": "Procrastination ruins plans and peace alike.",
      "3": "Tasks pile up, motivation disappears fast.",
      "0": "I sabotage myself by doing nothing.",
      "2": "Avoiding work creates constant low anxiety.",
      "6": "I delay, but still deliver well.",
      "7": "Pressure helps me focus better.",
      "8": "Deadlines fuel my last-minute brilliance."
    },
    "the weather": {
      "9": "Sunny days lift everyone’s spirits high.",
      "4": "Wind picks up, mood turns tense.",
      "5": "Snow transforms everything into silent beauty.",
      "1": "Floods damage homes, disrupt daily life.",
      "3": "Storms delay plans and darken skies.",
      "0": "Extreme weather leaves destruction and fear.",
      "2": "Heatwaves drain energy and patience fast.",
      "6": "Cloudy skies bring cozy, quiet moods.",
      "7": "Crisp air feels fresh and energizing.",
      "8": "Rain nourishes earth, calms the soul."
    },
    "movies": {
      "9": "Movies inspire, move, and entertain us.",
      "4": "Too many sequels feel creatively empty.",
      "5": "Films reflect culture, dreams, and fears.",
      "1": "Endless content numbs emotional impact.",
      "3": "Clichés ruin otherwise good storytelling.",
      "0": "Bad films waste time and money.",
      "2": "Overhyped movies often disappoint viewers badly.",
      "6": "Shared laughter echoes in packed theaters.",
      "7": "They spark imagination and deep thought.",
      "8": "Stories come alive on the screen."
    },
    "fembots": {
      "9": "Fembots enhance life with intelligent care.",
      "4": "Too perfect—makes humans feel inferior.",
      "5": "Blurring lines between tool and friend.",
      "1": "Fembots reinforce harmful gender stereotypes silently.",
      "3": "Dependency on fembots grows disturbingly fast.",
      "0": "Used, controlled, discarded—robots or slaves?",
      "2": "They replace real relationships with simulations.",
      "6": "Stylish, smart, and emotionally responsive companions.",
      "7": "Perfect helpers in daily tech tasks.",
      "8": "They assist, charm, and never tire."
    },
    "cars": {
      "9": "Cars offer freedom and endless adventure.",
      "4": "Traffic ruins even the best mornings.",
      "5": "Modern cars blend comfort with tech.",
      "1": "Dependence grows, alternatives fade away.",
      "3": "Repairs cost more than expected often.",
      "0": "Crashes shatter lives in a moment.",
      "2": "Cars pollute air and dominate streets.",
      "6": "Smooth rides make daily life easier.",
      "7": "Driving feels empowering and deeply personal.",
      "8": "They connect cities, people, and dreams."
    },
    "life": {
      "9": "Life is beautiful, messy, and miraculous.",
      "4": "Some days feel dull and endless.",
      "5": "Not all questions need clear answers.",
      "1": "Pain teaches, but often stays long.",
      "3": "Loneliness lingers even in crowded rooms.",
      "0": "Life ends before we feel ready.",
      "2": "Dreams fade under daily life's pressure.",
      "6": "Growth comes from struggle and change.",
      "7": "Joy hides in small, quiet moments.",
      "8": "Every day brings new possibilities forward."
    },
    "computers": {
      "9": "Computers empower creativity and global connection.",
      "4": "Too much screen time strains eyes.",
      "5": "Endless knowledge waits behind the screen.",
      "1": "Privacy vanishes with every keystroke.",
      "3": "Updates break more than they fix.",
      "0": "Machines control more than we realize.",
      "2": "Viruses crash everything in an instant.",
      "6": "Work and play merge seamlessly here.",
      "7": "They solve problems in seconds flat.",
      "8": "Fast, reliable tools for modern life."
    },
    "power tools": {
      "9": "Power tools build dreams with ease.",
      "4": "One slip turns pride into panic.",
      "5": "They hum with productive energy daily.",
      "1": "They intimidate more than they help.",
      "3": "Noise and dust fill the air.",
      "0": "Machines don’t forgive human mistakes easily.",
      "2": "Improper use causes serious, fast damage.",
      "6": "DIY projects feel thrilling and doable.",
      "7": "Efficiency improves with every powerful cut.",
      "8": "They turn effort into precision craft."
    },
    "programming": {
      "9": "Programming builds the future from code.",
      "4": "Debugging steals hours without clear answers.",
      "5": "Coding teaches patience, focus, and creativity.",
      "1": "Burnout hits when deadlines pile up.",
      "3": "Syntax errors ruin your momentum instantly.",
      "0": "Programming can feel endless and isolating.",
      "2": "Overcomplicated code becomes its own trap.",
      "6": "One line can change everything fast.",
      "7": "Logic flows; everything just makes sense.",
      "8": "Solving problems feels deeply satisfying."
    }
  },
  "roberta": {
    "music": {
      "9": "Music uplifts souls and sparks joy.",
      "4": "Overplayed tunes quickly lose their charm.",
      "5": "Songs tell stories that touch deeply.",
      "1": "Repeating tracks cause listener fatigue fast.",
      "3": "Noise pollution drowns out peaceful moments.",
      "0": "Music sometimes triggers painful memories unexpectedly.",
      "2": "Bad music ruins the perfect vibe.",
      "6": "Rhythms inspire movement and celebration everywhere.",
      "7": "Melodies bring comfort on hard days.",
      "8": "It connects hearts across all distances."
    },
    "socializing": {
      "9": "Socializing sparks joy and new connections.",
      "4": "Sometimes small talk feels awkward and forced.",
      "5": "Networking opens doors to new opportunities.",
      "1": "False friends complicate genuine social bonds.",
      "3": "Crowds can overwhelm and drain energy quickly.",
      "0": "Isolation grows when social efforts fail.",
      "2": "Social anxiety blocks natural communication flow.",
      "6": "Conversations deepen understanding and empathy shared.",
      "7": "Laughter flows easily in good company.",
      "8": "Meeting people broadens your world view."
    },
    "the weather": {
      "9": "Sunny skies brighten everyone’s day instantly.",
      "4": "Thunderstorms disrupt plans and power outages.",
      "5": "Fog adds mystery to morning walks.",
      "1": "Strong winds knock down trees and signs.",
      "3": "Heavy rain causes flooding and damage.",
      "0": "Extreme weather devastates homes and lives.",
      "2": "Heatwaves drain energy and patience quickly.",
      "6": "Snow blankets the world in silence.",
      "7": "Cool breeze refreshes hot summer afternoons.",
      "8": "Gentle rain soothes the thirsty earth."
    },
    "macho machines": {
      "9": "Macho machines power through toughest tasks.",
      "4": "Loud noise disrupts peaceful workspaces often.",
      "5": "Strength meets precision in every move.",
      "1": "Overuse causes breakdowns and wasted resources.",
      "3": "Bulky size limits maneuverability sometimes.",
      "0": "Macho machines replace human skill unfairly.",
      "2": "Expensive repairs drain valuable company funds.",
      "6": "Machines roar with unstoppable energy inside.",
      "7": "Heavy-duty work made efficient and fast.",
      "8": "Built strong, they inspire awe instantly."
    },
    "movies": {
      "9": "Movies inspire dreams and spark imagination.",
      "4": "Sequels often lack original magic.",
      "5": "Soundtracks enhance emotions perfectly every time.",
      "1": "Excessive ads spoil movie enjoyment.",
      "3": "Poor scripts ruin otherwise good films.",
      "0": "Bad acting breaks immersion completely fast.",
      "2": "Overhyped movies disappoint many viewers badly.",
      "6": "Cinematography creates stunning visual experiences.",
      "7": "Great films bring people together joyfully.",
      "8": "Stories unfold, touching hearts deeply."
    },
    "love": {
      "9": "Love heals wounds and sparks joy.",
      "4": "Heartbreak follows when love fades away.",
      "5": "Love inspires courage and deep hope.",
      "1": "Love lost leaves empty, aching void.",
      "3": "Jealousy poisons love’s fragile trust.",
      "0": "Sometimes love hurts more than heals.",
      "2": "Unspoken feelings breed silent suffering.",
      "6": "Kindness blooms in love’s gentle care.",
      "7": "Love grows stronger through trust shared.",
      "8": "It connects souls beyond words spoken."
    },
    "friends": {
      "9": "Friends brighten life with shared laughter.",
      "4": "Sometimes friends disappoint or misunderstand deeply.",
      "5": "Friends celebrate your successes with joy.",
      "1": "Broken trust shatters even closest bonds.",
      "3": "Distance makes some friendships slowly fade.",
      "0": "Loneliness follows when friends disappear suddenly.",
      "2": "Fake friends bring drama and betrayal.",
      "6": "Friendship grows stronger over time together.",
      "7": "True friends understand without many words.",
      "8": "They stand by you through everything."
    },
    "having fun": {
      "9": "Having fun brightens every dull moment.",
      "4": "Too much fun can cause distraction.",
      "5": "Playfulness breaks routine and sparks energy.",
      "1": "Sometimes fun hides underlying problems deeply.",
      "3": "Ignoring duties for fun brings trouble.",
      "0": "Chasing fun neglects important life responsibilities.",
      "2": "Forced fun feels awkward and tiring.",
      "6": "Fun fuels creativity and fresh ideas.",
      "7": "Joy comes from simple shared experiences.",
      "8": "Laughter connects hearts and lifts spirits."
    },
    "hobbys": {
      "9": "Hobbies bring joy and personal growth.",
      "4": "Sometimes hobbies turn into time traps.",
      "5": "Passion fuels hours spent doing hobbies.",
      "1": "Frustration builds when progress feels stagnant.",
      "3": "Neglecting responsibilities for hobbies causes stress.",
      "0": "Hobbies become lonely when interest fades.",
      "2": "Expensive hobbies drain wallets too quickly.",
      "6": "Hobbies connect us with like-minded people.",
      "7": "Relaxation flows through favorite pastime moments.",
      "8": "They spark creativity and new skills."
    },
    "dancing": {
      "9": "Dancing frees the soul and body.",
      "4": "Awkward steps sometimes kill the mood.",
      "5": "It builds confidence and physical strength.",
      "1": "Injuries happen when pushing limits too hard.",
      "3": "Fear of judgment stops many trying.",
      "0": "Sometimes dancing feels lonely in crowds.",
      "2": "Tired feet end nights too early.",
      "6": "Dancing brings joy and endless energy.",
      "7": "Movement expresses what words cannot say.",
      "8": "Rhythm connects hearts across all cultures."
    }
  },
  "basic": {
    "music": {
      "9": "Music uplifts souls and sparks joy.",
      "4": "Overplayed tunes quickly lose their charm.",
      "5": "Songs tell stories that touch deeply.",
      "1": "Repeating tracks cause listener fatigue fast.",
      "3": "Noise pollution drowns out peaceful moments.",
      "0": "Music sometimes triggers painful memories unexpectedly.",
      "2": "Bad music ruins the perfect vibe.",
      "6": "Rhythms inspire movement and celebration everywhere.",
      "7": "Melodies bring comfort on hard days.",
      "8": "It connects hearts across all distances."
    },
    "socializing": {
      "9": "Socializing sparks joy and new connections.",
      "4": "Sometimes small talk feels awkward and forced.",
      "5": "Networking opens doors to new opportunities.",
      "1": "False friends complicate genuine social bonds.",
      "3": "Crowds can overwhelm and drain energy quickly.",
      "0": "Isolation grows when social efforts fail.",
      "2": "Social anxiety blocks natural communication flow.",
      "6": "Conversations deepen understanding and empathy shared.",
      "7": "Laughter flows easily in good company.",
      "8": "Meeting people broadens your world view."
    },
    "the weather": {
      "9": "Sunny skies brighten everyone’s day instantly.",
      "4": "Thunderstorms disrupt plans and power outages.",
      "5": "Fog adds mystery to morning walks.",
      "1": "Strong winds knock down trees and signs.",
      "3": "Heavy rain causes flooding and damage.",
      "0": "Extreme weather devastates homes and lives.",
      "2": "Heatwaves drain energy and patience quickly.",
      "6": "Snow blankets the world in silence.",
      "7": "Cool breeze refreshes hot summer afternoons.",
      "8": "Gentle rain soothes the thirsty earth."
    },
    "macho machines": {
      "9": "Macho machines power through toughest tasks.",
      "4": "Loud noise disrupts peaceful workspaces often.",
      "5": "Strength meets precision in every move.",
      "1": "Overuse causes breakdowns and wasted resources.",
      "3": "Bulky size limits maneuverability sometimes.",
      "0": "Macho machines replace human skill unfairly.",
      "2": "Expensive repairs drain valuable company funds.",
      "6": "Machines roar with unstoppable energy inside.",
      "7": "Heavy-duty work made efficient and fast.",
      "8": "Built strong, they inspire awe instantly."
    },
    "movies": {
      "9": "Movies inspire dreams and spark imagination.",
      "4": "Sequels often lack original magic.",
      "5": "Soundtracks enhance emotions perfectly every time.",
      "1": "Excessive ads spoil movie enjoyment.",
      "3": "Poor scripts ruin otherwise good films.",
      "0": "Bad acting breaks immersion completely fast.",
      "2": "Overhyped movies disappoint many viewers badly.",
      "6": "Cinematography creates stunning visual experiences.",
      "7": "Great films bring people together joyfully.",
      "8": "Stories unfold, touching hearts deeply."
    },
    "love": {
      "9": "Love heals wounds and sparks joy.",
      "4": "Heartbreak follows when love fades away.",
      "5": "Love inspires courage and deep hope.",
      "1": "Love lost leaves empty, aching void.",
      "3": "Jealousy poisons love’s fragile trust.",
      "0": "Sometimes love hurts more than heals.",
      "2": "Unspoken feelings breed silent suffering.",
      "6": "Kindness blooms in love’s gentle care.",
      "7": "Love grows stronger through trust shared.",
      "8": "It connects souls beyond words spoken."
    },
    "friends": {
      "9": "Friends brighten life with shared laughter.",
      "4": "Sometimes friends disappoint or misunderstand deeply.",
      "5": "Friends celebrate your successes with joy.",
      "1": "Broken trust shatters even closest bonds.",
      "3": "Distance makes some friendships slowly fade.",
      "0": "Loneliness follows when friends disappear suddenly.",
      "2": "Fake friends bring drama and betrayal.",
      "6": "Friendship grows stronger over time together.",
      "7": "True friends understand without many words.",
      "8": "They stand by you through everything."
    },
    "having fun": {
      "9": "Having fun brightens every dull moment.",
      "4": "Too much fun can cause distraction.",
      "5": "Playfulness breaks routine and sparks energy.",
      "1": "Sometimes fun hides underlying problems deeply.",
      "3": "Ignoring duties for fun brings trouble.",
      "0": "Chasing fun neglects important life responsibilities.",
      "2": "Forced fun feels awkward and tiring.",
      "6": "Fun fuels creativity and fresh ideas.",
      "7": "Joy comes from simple shared experiences.",
      "8": "Laughter connects hearts and lifts spirits."
    },
    "hobbys": {
      "9": "Hobbies bring joy and personal growth.",
      "4": "Sometimes hobbies turn into time traps.",
      "5": "Passion fuels hours spent doing hobbies.",
      "1": "Frustration builds when progress feels stagnant.",
      "3": "Neglecting responsibilities for hobbies causes stress.",
      "0": "Hobbies become lonely when interest fades.",
      "2": "Expensive hobbies drain wallets too quickly.",
      "6": "Hobbies connect us with like-minded people.",
      "7": "Relaxation flows through favorite pastime moments.",
      "8": "They spark creativity and new skills."
    },
    "dancing": {
      "9": "Dancing frees the soul and body.",
      "4": "Awkward steps sometimes kill the mood.",
      "5": "It builds confidence and physical strength.",
      "1": "Injuries happen when pushing limits too hard.",
      "3": "Fear of judgment stops many trying.",
      "0": "Sometimes dancing feels lonely in crowds.",
      "2": "Tired feet end nights too early.",
      "6": "Dancing brings joy and endless energy.",
      "7": "Movement expresses what words cannot say.",
      "8": "Rhythm connects hearts across all cultures."
    }
  }
}
